packageExtensions:
  "@apollo/gateway@*":
    dependencies:
      node-fetch: "*"
  "@nestjs/graphql@*":
    peerDependencies:
      "@apollo/federation": "*"
      apollo-server-express: "*"
  typeorm@*:
    peerDependencies:
      pg: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs
